// Generated by scripts/make-tray-icon.py — do not edit by hand.
/** The menu bar icon as a macOS template image (black + alpha), PNG, base64, by scale factor. */
export const TRAY_ICON_PNG_BASE64: Record<1 | 2, string> = {
  1: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAWUlEQVR42mNgoDLQBOJiIG7AgYuharCCHCD+TyTOwWbzfxIxikuKyTCgGNmABhyKlkExNrkGQgZYIMlbkGrAMiyBvIyuBlDsBZIDkeJopDghUZyUqZKZyAIA+8OMLXPemd0AAAAASUVORK5CYII=',
  2: 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAq0lEQVR42u2Xyw2AIAxAGcCJmIJVOLIQu7ABG7ABV+yhHsWi6SeGJu9CAn0BLcW5HYbjABJQgA6MRTrOTbjWUgSgvUh6R8M1yckHE4Gy7Y1RoD0dR2JMfpFmAkVAoMwEuoBAnwkMIT4LVCACHok4JiKQJ/Mzt0Al1JHKKRAJApFTwBME/K8F1I9A/SNU/w1NFCLWUqx+Galfx+oNiXpLpt6UmmjLTTxMdojFCbxWLKOs/sRrAAAAAElFTkSuQmCC'
}
