#!/usr/bin/env python3
"""Draws the menu bar icon — the brand mark as a macOS template image: a black
rounded square with a hole in the middle — at 1x (16 px) and 2x (32 px), and
writes them as base64 PNGs into src/main/windows/trayIcon.ts.

Pure standard library, so it runs anywhere Python 3 does.
"""
import base64
import math
import struct
import sys
import zlib

POINTS = 16
# In points; the body leaves a little room so the icon sits like the system's own.
BODY = 13.0
RADIUS = 3.6
HOLE_RADIUS = 2.4


def rounded_rect_distance(x: float, y: float) -> float:
    """Signed distance to the body's outline, in points: negative inside."""
    half = BODY / 2
    qx = abs(x - POINTS / 2) - (half - RADIUS)
    qy = abs(y - POINTS / 2) - (half - RADIUS)
    outside = math.hypot(max(qx, 0.0), max(qy, 0.0))
    return outside + min(max(qx, qy), 0.0) - RADIUS


def coverage(distance: float, scale: int) -> float:
    """Anti-aliased coverage of a pixel whose centre is `distance` points from an edge."""
    return min(max(0.5 - distance * scale, 0.0), 1.0)


def alpha(x: int, y: int, scale: int) -> int:
    cx, cy = (x + 0.5) / scale, (y + 0.5) / scale
    body = coverage(rounded_rect_distance(cx, cy), scale)
    hole = coverage(math.hypot(cx - POINTS / 2, cy - POINTS / 2) - HOLE_RADIUS, scale)
    return round(body * (1.0 - hole) * 255)


def chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def png(scale: int) -> bytes:
    size = POINTS * scale
    rows = bytearray()
    for y in range(size):
        rows.append(0)
        for x in range(size):
            rows += bytes([0, 0, 0, alpha(x, y, scale)])
    header = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(bytes(rows), 9)) + chunk(b"IEND", b"")


def main(path: str) -> None:
    lines = [
        "// Generated by scripts/make-tray-icon.py — do not edit by hand.",
        "/** The menu bar icon as a macOS template image (black + alpha), PNG, base64, by scale factor. */",
        "export const TRAY_ICON_PNG_BASE64: Record<1 | 2, string> = {",
        f"  1: '{base64.b64encode(png(1)).decode()}',",
        f"  2: '{base64.b64encode(png(2)).decode()}'",
        "}",
        "",
    ]
    with open(path, "w") as file:
        file.write("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "src/main/windows/trayIcon.ts")
